MyFinalProject/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyFinalProject.Data;
using MyFinalProject.Models;
using MyFinalProject.Repositiories;
using System.Data;

namespace MyFinalProject.Controllers
{
    [Authorize(Roles = "admin")]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ICategoryRep _rep;

        public CategoryController(ApplicationDbContext context, ICategoryRep rep)
        {
            _context = context;
            _rep = rep;
        }

        public IActionResult Show()
        {
            return View(_rep.ShowAll());
        }


        [AllowAnonymous] // do not use the security show the page , every one can show this View
        public IActionResult create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult create(Category inf)
        {
            MemoryStream stream = new MemoryStream();

            //file data carry 
            inf.CatImage.CopyTo(stream);

            //ms to byte array

            inf.Img = stream.ToArray();

            //table name



            _rep.Create(inf);
            return RedirectToAction("Show");



            
        }



        public IActionResult Edit(int id)
        {
            return View(_rep.ShowCat(id));
        }

        [HttpPost]
        public IActionResult Edit(Category u)
        {
            _rep.Update(u);
            return RedirectToAction("Show");
        }


        public IActionResult Delete(int ID)
        {
            _rep.Delete(ID);
            return RedirectToAction("Show");
        }


        public IActionResult Details(int id)
        {

            return View(_rep.ShowCatById(id));
        }



        public IActionResult Index()
        {
            return View();
        }
    }
}

MyFinalProject/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using MyFinalProject.Data;
using MyFinalProject.Models;
using MyFinalProject.Models.VMs;
using MyFinalProject.Repositiories;

namespace MyFinalProject.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IProductRep _rep;

        public ProductController(ApplicationDbContext context, IProductRep rep)
        {
            _context = context;
            _rep = rep;
        }

        public IActionResult _ListAll()
        {

            return View(_context.Prodtbl);
        }

        public IActionResult AddToCart(int prodId)

        {
              _context.tblOrders.Add(new Models.Orders { prodID = prodId });
            _context.SaveChanges();
            return RedirectToAction("_ListAll");
        }

        public IActionResult ShowCart()
        {
            var res = (from c in _context.tblOrders
                       join k in _context.Prodtbl
                       on c.prodID equals k.prodID
                       select new OrderVM
                       {
                           prodName = k.prodName,
                           prodPrice = k.prodPrice,


                       }
                       ).ToList();

            return PartialView("_Cart", res);
        }


        public IActionResult Show()
        {

            return View(_rep.ShowAll());
        }


        public IActionResult create()
        {
            // _context.Prodtbl.ToList();
            //ViewBag.cat = _context.Cattbl.ToList();
            return View();

        }

        [HttpPost]
        public IActionResult create(Product inf)
        {

            MemoryStream stream = new MemoryStream();

            //file data carry 
            inf.prodImage.CopyTo(stream);

            //ms to byte array

            inf.Img = stream.ToArray();

            //table name



            _rep.Create(inf);
            return RedirectToAction("Show");
        }

        public IActionResult Edit(int id)
        {
            return View(_rep.ShowProd(id));
        }

        [HttpPost]
        public IActionResult Edit(Product u)
        {
            _rep.Update(u);
            return RedirectToAction("Show");
        }



        public IActionResult Delete(int ID)
        {
            _rep.Delete(ID);
            return RedirectToAction("Show");
        }


        public IActionResult Details(int id)
        {

            return View(_rep.ShowProdById(id));
        }


        public IActionResult Index()
        {
            return View();
        }
    }

}

MyFinalProject/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyFinalProject.Data;
using MyFinalProject.Models;
using MyFinalProject.Repositiories;
using System.Data;

namespace MyFinalProject.Controllers
{
    [Authorize(Roles = "user")]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IUserRep _rep;
        public UserController(ApplicationDbContext context,IUserRep rep)
        {
            _context = context;
            _rep = rep;
        }
       

      
        public IActionResult Show()
        {
            return View(_rep.ShowAll().ToList());
        }


        public IActionResult create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult create(User id)
        {
            _rep.Create(id);
            return RedirectToAction("Show");
        }



        public IActionResult Edit(int id)
        {
            return View(_rep.ShowUser(id));
        }

        [HttpPost]
        public IActionResult Edit(User u)
        {
            _rep.Update(u);
            return RedirectToAction("Show");
        }

        public IActionResult Delete(int ID)
        {
            _rep.Delete(ID);
            return RedirectToAction("Show");
        }


        public IActionResult Details(int id)
        {
            
            return View(_rep.ShowUserById(id));
        }


        public IActionResult Index()
        {
            return View();
        }
    }
}

MyFinalProject/Views/Shared/AdminLayout.cshtml
<!doctype html>
<html lang="en">

  <head>
   @* <title>Handyman &mdash; Free Website Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">*@

    <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="~/Admin/fonts/icomoon/style.css">

    <link rel="stylesheet" href="~/Admin/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Admin/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/Admin/css/jquery.fancybox.min.css">
    <link rel="stylesheet" href="~/Admin/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Admin/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/Admin/fonts/flaticon/font/flaticon.css">
    <link rel="stylesheet" href="~/Admin/css/aos.css">

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="~/Admin/css/style.css">

  </head>

  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">


    <div class="site-wrap" id="home-section">

      <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
          <div class="site-mobile-menu-close mt-3">
            <span class="icon-close2 js-menu-toggle"></span>
          </div>
        </div>
        <div class="site-mobile-menu-body"></div>
      </div>



      <header class="site-navbar site-navbar-target" role="banner">
            
        <div class="container">
          <div class="row align-items-center position-relative">
          
            <div class="col-3 ">
              <div class="site-logo">
                
              </div>
            </div>

            <div class="col-9  text-right">

                    <div>
            <partial name="_loginPartial" /></partial>
        </div>

              <span class="d-inline-block d-lg-none"><a href="#" class="text-white site-menu-toggle js-menu-toggle py-5 text-white"><span class="icon-menu h3 text-white"></span></a></span>



              <nav class="site-navigation text-right ml-auto d-none d-lg-block" role="navigation">
                <ul class="site-menu main-menu js-clone-nav ml-auto ">
                  <li class="active"><a href="index.html" class="nav-link">Home</a></li>
                  <li><a asp-action="Show" asp-controller="Category">Category</a></li>
                 
                  <li><a asp-action="Show" asp-controller="Product">Service</a></li>
                   <li><a asp-action="Show" asp-controller="User">Userend</a></li>


                  
                  <li><a href="blog.html" class="nav-link">Blog</a></li>
                  <li><a href="contact.html" class="nav-link">Contact</a></li>

                </ul>
              </nav>
            </div>


          </div>
        </div>

      </header>
      

      <div class="ftco-blocks-cover-1">
      <div class="ftco-cover-1 overlay"  style="background-image: url('~/Admin/images/hero_1.jpg')">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-lg-5">
              <h1 class="line-bottom">Perfection is always in our mind.</h1>
            </div>
            <div class="col-lg-5 ml-auto">

            </div>
          </div>
        </div>
      </div>
    </div>


    

    
              
          
          

    
   
    <div class="site-section">
      <div class="container">
        <div class="row mb-4">

          <div class="col-md-4 mx-auto">
            <h2 class="line-bottom text-center">Our Projects</h2>
          </div>

        </div>

        <div class="row">
          <div class="col-md-6 mb-5 mb-lg-5 col-lg-4">
            <div class="project-item">

              <img src="~/Admin/images/img_1.jpg" alt="Image" class="img-fluid">

              <div class="project-item-overlay">
                <a class="category" href="#">Renovate</a>
                <span class="plus">
                  <span class="icon-plus"></span>
                </span>

                <a href="#" class="project-title"><span>Renovate the house</span></a>
              </div>

            </div>
          </div>

          <div class="col-md-6 mb-5 mb-lg-5 col-lg-4">
            <div class="project-item">

              <img src="~/Admin/images/img_2.jpg" alt="Image" class="img-fluid">

              <div class="project-item-overlay">
                <a class="category" href="#">Renovate</a>
                <span class="plus">
                  <span class="icon-plus"></span>
                </span>

                <a href="#" class="project-title"><span>Renovate the house 2</span></a>
              </div>

            </div>
          </div>

          <div class="col-md-6 mb-5 mb-lg-5 col-lg-4">
            <div class="project-item">

              <img src="~/Admin/images/img_3.jpg" alt="Image" class="img-fluid">

              <div class="project-item-overlay">
                <a class="category" href="#">Renovate</a>
                <span class="plus">
                  <span class="icon-plus"></span>
                </span>

                <a href="#" class="project-title"><span>Renovate the house 2</span></a>
              </div>

            </div>
          </div>

          <div class="col-md-6 mb-5 mb-lg-5 col-lg-4">
            <div class="project-item">

              <img src="~/Admin/images/img_4.jpg" alt="Image" class="img-fluid">

              <div class="project-item-overlay">
                <a class="category" href="#">Renovate</a>
                <span class="plus">
                  <span class="icon-plus"></span>
                </span>

                <a href="#" class="project-title"><span>Renovate the house</span></a>
              </div>

            </div>
          </div>

          <div class="col-md-6 mb-5 mb-lg-5 col-lg-4">
            <div class="project-item">

              <img src="~/Admin/images/img_1.jpg" alt="Image" class="img-fluid">

              <div class="project-item-overlay">
                <a class="category" href="#">Renovate</a>
                <span class="plus">
                  <span class="icon-plus"></span>
                </span>

                <a href="#" class="project-title"><span>Renovate the house 2</span></a>
              </div>

            </div>
          </div>

          <div class="col-md-6 mb-5 mb-lg-5 col-lg-4">
            <div class="project-item">

              <img src="~/Admin/images/img_2.jpg" alt="Image" class="img-fluid">

              <div class="project-item-overlay">
                <a class="category" href="#">Renovate</a>
                <span class="plus">
                  <span class="icon-plus"></span>
                </span>

                <a href="#" class="project-title"><span>Renovate the house 2</span></a>
              </div>

            </div>
          </div>


         

          <div>

            <partial name="_LoginPartial"></partial>
        </div>

          @RenderBody();

   


    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-3">
            <h2 class="footer-heading mb-4">About Us</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis impedit, odit minima repellat, doloribus alias amet consequatur inventore.</p>
          </div>
          <div class="col-lg-8 ml-auto">
            <div class="row">
              <div class="col-lg-3">
                <h2 class="footer-heading mb-4">Quick Links</h2>
                <ul class="list-unstyled">
                  <li><a href="#">About abc Us</a></li>
                  <li><a href="#">Testimabconials</a></li>
                  <li><a href="#">Termsabc of Service</a></li>
                  <li><a href="#">Privabcacy</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
              </div>
              <div class="col-lg-3">
                <h2 class="footer-heading mb-4">Quick Links</h2>
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Testimonials</a></li>
                  <li><a href="#">Terms of Service</a></li>
                  <li><a href="#">Privacy</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
              </div>
              <div class="col-lg-3">
                <h2 class="footer-heading mb-4">Quick Links</h2>
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Testimonials</a></li>
                  <li><a href="#">Terms of Service</a></li>
                  <li><a href="#">Privacy</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
              </div>
              <div class="col-lg-3">
                <h2 class="footer-heading mb-4">Quick Links</h2>
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Testimonials</a></li>
                  <li><a href="#">Terms of Service</a></li>
                  <li><a href="#">Privacy</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <div class="border-top pt-5">
              <p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
            </div>
          </div>

        </div>
      </div>
    </footer>

    </div>

    <script src="~/Admin/js/jquery-3.3.1.min.js"></script>
    <script src="~/Admin/js/popper.min.js"></script>
    <script src="~/Admin/js/bootstrap.min.js"></script>
    <script src="~/Admin/js/owl.carousel.min.js"></script>
    <script src="~/Admin/js/jquery.sticky.js"></script>
    <script src="~/Admin/js/jquery.waypoints.min.js"></script>
    <script src="~/Admin/js/jquery.animateNumber.min.js"></script>
    <script src="~/Admin/js/jquery.animateNumber.min.js"></script>
    <script src="~/Admin/js/jquery.fancybox.min.js"></script>
    <script src="~/Admin/js/jquery.easing.1.3.js"></script>
    <script src="~/Admin/js/bootstrap-datepicker.min.js"></script>
    <script src="~/Admin/js/aos.js"></script>

    <script src="~/Admin/js/main.js"></script>

  </body>

</html>

MyFinalProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyFinalProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyFinalProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
       <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyFinalProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
       

        <div class="col-9  text-right">

                    <div>
            <partial name="_loginPartial" /></partial>
        </div>

        
       

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MyFinalProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MyFinalProject/Views/Shared/color.cshtml
<!doctype html>
<html lang="en">

  <head>
    <title>Handyman &mdash; Free Website Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="fonts/icomoon/style.css">

    <link rel="stylesheet" href="~/Admin/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Admin/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/Admin/css/jquery.fancybox.min.css">
    <link rel="stylesheet" href="~/Admin/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Admin/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/Admin/fonts/flaticon/font/flaticon.css">
    <link rel="stylesheet" href="~/Admin/css/aos.css">

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="~/Admin/css/style.css">

  </head>

  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">


    

      

            <div class="col-9  text-right">

              

              <span class="d-inline-block d-lg-none"><a href="#" class="text-white site-menu-toggle js-menu-toggle py-5 text-white"><span class="icon-menu h3 text-white"></span></a></span>



            


          </div>
        </div>

      </header>


      <div class="ftco-blocks-cover-1">
      <div class="ftco-cover-1 overlay" style="background-image: url('~/Admin/images/hero_1.jpg')">
 


    

    
              
          
          


   

          



          @RenderBody();

   


   

    <script src="~/Admin/js/jquery-3.3.1.min.js"></script>
    <script src="~/Admin/js/popper.min.js"></script>
    <script src="~/Admin/js/bootstrap.min.js"></script>
    <script src="~/Admin/js/owl.carousel.min.js"></script>
    <script src="~/Admin/js/jquery.sticky.js"></script>
    <script src="~/Admin/js/jquery.waypoints.min.js"></script>
    <script src="~/Admin/js/jquery.animateNumber.min.js"></script>
    <script src="~/Admin/js/jquery.animateNumber.min.js"></script>
    <script src="~/Admin/js/jquery.fancybox.min.js"></script>
    <script src="~/Admin/js/jquery.easing.1.3.js"></script>
    <script src="~/Admin/js/bootstrap-datepicker.min.js"></script>
    <script src="~/Admin/js/aos.js"></script>

    <script src="~/Admin/js/main.js"></script>

  </body>

</html>